### ISSUE TITLE
[FEATURE REQ]global multiplier

### ISSUE THREAD

**Issue by paddywaan** [blaxxun-boop/SteadyRegeneration#1]
As a server owner I want to be able to easily increase or decrease the global stamina regeneration rate given by your mod, such that it keeps the scaling you have decided to be accurate, but applies only a % of that value across all regen items.

For example, a Mushroom has 0.45 value by default. If I set the global multiplier to 0.1, I would expect the mushroom to give 0.045

**Comment by blaxxun-boop** [comment]
Hey,

probably the wrong mod, but I've added something like this for Stamina Regeneration from Food.

Cheers.
