### ISSUE TITLE
Clientside? or both? 

### ISSUE THREAD

**Issue by Funky18229** [blaxxun-boop/SteadyRegeneration#2]
blaxxun, would you be so kind to please add info to your mods, if they are client side or both server and client?  I am trying to get rid of any mods that dont need to be on my server and i just want to make sure .

**Comment by blaxxun-boop** [comment]
Hey,

that's fairly simple. If it has a cfg file, you wanna have it on the server as well. If it doesn't then it's client side only.
Steady Regeneration doesn't have a cfg file, so it doesn't go on the server. (Just note that this is only true for my mods)

And all the mods that can be installed on a server, have something like
"Can be installed on a server, to enforce the configuration."
in their description already.

Cheers.
