### ISSUE TITLE
Regen and Epic Loot

### ISSUE THREAD

**Issue by UberMorgott** [blaxxun-boop/SteadyRegeneration#4]
Hello!
The Epic loot mod has a property to increase regen.
So it stops working with Steady regen mod.
Steady regen comes only from the base value or food.

**Comment by blaxxun-boop** [comment]
Yeah, I don't care about Epic Loot at all, sorry. It causes such a ridiculous amount of issues, it's insane. Just replace it with Jewelcrafting and start having fun.

**Comment by UberMorgott** [comment]
Thank you for your reply. Too bad it won't work out)
